"use client";

import { useEffect, useState } from "react";
import {
    FileText,
    Table as TableIcon,
    Search,
    CheckCircle,
    Clock,
    BookOpen,
    Users,
    AlertCircle
} from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

// --- Interfaces ---
interface Request {
    _id: string;
    status: string;
    returnDate?: string;
    returned: boolean;
    fineAmount: number;
    finePaid: boolean;
    createdAt: string;
    requestedBy: {
        name: string;
        email: string;
        rollNumber?: string;
        staffId?: string;
    };
    bookId: {
        title: string;
        author: string;
        bookId: string;
    };
}

interface Issue {
    _id: string;
    issueDate: string;
    returnDate: string;
    returned: boolean;
    fineAmount: number;
    finePaid: boolean;
    studentId: {
        name: string;
        email: string;
        rollNumber?: string;
        staffId?: string;
    };
    bookId: {
        title: string;
        author: string;
        bookId: string;
    };
}

export default function AdminManagement() {
    const [requests, setRequests] = useState<Request[]>([]);
    const [issues, setIssues] = useState<Issue[]>([]);
    const [loading, setLoading] = useState(true);
    const [activeTab, setActiveTab] = useState<"requests" | "issues">("requests");
    const [searchTerm, setSearchTerm] = useState("");

    useEffect(() => {
        const fetchAllData = async () => {
            try {
                const [reqRes, issueRes] = await Promise.all([
                    fetch("/api/admin/fetch-requests"),
                    fetch("/api/admin/fetch-issues"),
                ]);
                const reqData = await reqRes.json();
                const issueData = await issueRes.json();
                setRequests(reqData.requests || []);
                setIssues(issueData.issues || []);
            } catch (error) {
                console.error(error);
            }
            setLoading(false);
        };
        fetchAllData();
    }, []);

    // Statistics
    const totalRequests = requests.length;
    const pendingRequests = requests.filter(r => r.status === 'pending').length;
    const approvedRequests = requests.filter(r => r.status === 'approved').length;

    const totalIssues = issues.length;
    const activeIssues = issues.filter(i => !i.returned).length;
    const overdueIssues = issues.filter(i => !i.returned && new Date(i.returnDate) < new Date()).length;

    // Export functions
    const handleExcelExport = () => {
        const data = activeTab === "requests" ? requests : issues;
        const worksheet = XLSX.utils.json_to_sheet(data);
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, activeTab);
        XLSX.writeFile(workbook, `Library_${activeTab}_${new Date().toISOString().split('T')[0]}.xlsx`);
    };

    const handlePDFExport = () => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        const pageHeight = doc.internal.pageSize.height;

        // Header background
        doc.setFillColor(248, 250, 252);
        doc.rect(0, 0, pageWidth, 45, 'F');

        // Add logo on left side
        const logoUrl = '/login-card-bg.png';
        const logoWidth = 35;
        const logoHeight = 35;

        try {
            doc.addImage(logoUrl, 'PNG', 15, 5, logoWidth, logoHeight);
        } catch (error) {
            // Fallback if logo fails
            doc.setFontSize(20);
            doc.setTextColor(0, 70, 150);
            doc.setFont('helvetica', 'bold');
            doc.text('📚', 25, 25);
        }

        // Right side header details
        doc.setFontSize(20);
        doc.setTextColor(0, 70, 150);
        doc.setFont('helvetica', 'bold');
        doc.text('SMART LIBRARY SYSTEM', pageWidth - 100, 15);

        doc.setFontSize(14);
        doc.setTextColor(60, 60, 60);
        doc.setFont('helvetica', 'bold');
        doc.text(`${activeTab.toUpperCase()} REPORT`, pageWidth - 100, 25);

        // Horizontal line
        doc.setDrawColor(0, 70, 150);
        doc.setLineWidth(0.5);
        doc.line(15, 45, pageWidth - 15, 45);

        // Report metadata in two columns
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.setFont('helvetica', 'normal');

        // Left column metadata
        doc.text(`Generated On:`, 15, 55);
        doc.text(`Generated By:`, 15, 62);
        doc.text(`Report Type:`, 15, 69);

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text(`${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 50, 55);
        doc.text('Administrator', 50, 62);
        doc.text(`${activeTab.charAt(0).toUpperCase() + activeTab.slice(1)} Management`, 50, 69);

        // Right column metadata
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(80, 80, 80);
        doc.text(`Total Records:`, pageWidth - 80, 55);
        doc.text(`Active Records:`, pageWidth - 80, 62);
        doc.text(`Date Range:`, pageWidth - 80, 69);

        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        const totalRecords = activeTab === "requests" ? requests.length : issues.length;
        const activeRecords = activeTab === "requests"
            ? requests.filter(r => r.status === 'pending').length
            : issues.filter(i => !i.returned).length;

        doc.text(`${totalRecords}`, pageWidth - 40, 55);
        doc.text(`${activeRecords}`, pageWidth - 40, 62);
        doc.text('Current Month', pageWidth - 40, 69);

        const tableData = activeTab === "requests"
            ? requests.map(r => [
                r.requestedBy.name,
                r.bookId.title,
                r.status.toUpperCase(),
                `₹${r.fineAmount}`,
                new Date(r.createdAt).toLocaleDateString()
            ])
            : issues.map(i => [
                i.studentId.name,
                i.bookId.title,
                new Date(i.issueDate).toLocaleDateString(),
                new Date(i.returnDate).toLocaleDateString(),
                i.returned ? "RETURNED" : "ACTIVE",
                `₹${i.fineAmount}`
            ]);

        autoTable(doc, {
            head: activeTab === "requests"
                ? [["USER NAME", "BOOK TITLE", "STATUS", "FINE (₹)", "REQUEST DATE"]]
                : [["STUDENT NAME", "BOOK TITLE", "ISSUE DATE", "DUE DATE", "STATUS", "FINE (₹)"]],
            body: tableData,
            startY: 80,
            styles: {
                fontSize: 9,
                textColor: [0, 0, 0],
                lineColor: [200, 200, 200],
                lineWidth: 0.1,
                cellPadding: 5
            },
            headStyles: {
                fillColor: [0, 70, 150],
                textColor: [255, 255, 255],
                fontStyle: 'bold',
                fontSize: 10,
                halign: 'center'
            },
            columnStyles: activeTab === "requests"
                ? {
                    0: { cellWidth: 35 },
                    1: { cellWidth: 60 },
                    2: { cellWidth: 25 },
                    3: { cellWidth: 20 },
                    4: { cellWidth: 25 }
                }
                : {
                    0: { cellWidth: 30 },
                    1: { cellWidth: 50 },
                    2: { cellWidth: 25 },
                    3: { cellWidth: 25 },
                    4: { cellWidth: 20 },
                    5: { cellWidth: 20 }
                },
            alternateRowStyles: {
                fillColor: [249, 250, 251]
            },
            didDrawPage: function (data) {
                // Header on each page
                doc.setFillColor(248, 250, 252);
                doc.rect(0, 0, pageWidth, 45, 'F');

                try {
                    doc.addImage(logoUrl, 'PNG', 15, 5, logoWidth, logoHeight);
                } catch (error) { }

                doc.setFontSize(20);
                doc.setTextColor(0, 70, 150);
                doc.setFont('helvetica', 'bold');
                doc.text('SMART LIBRARY SYSTEM', pageWidth - 100, 15);

                doc.setFontSize(14);
                doc.setTextColor(60, 60, 60);
                doc.text(`${activeTab.toUpperCase()} REPORT`, pageWidth - 100, 25);

                doc.setDrawColor(0, 70, 150);
                doc.setLineWidth(0.5);
                doc.line(15, 45, pageWidth - 15, 45);
            }
        });

        // Summary footer
        const finalY = (doc as any).lastAutoTable.finalY || 80;


        // Page numbers with total pages
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);

            // Footer line
            doc.setDrawColor(200, 200, 200);
            doc.setLineWidth(0.1);
            doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.setFont('helvetica', 'normal');

            // Left footer
            doc.text('Smart Library Management System', 15, pageHeight - 8);

            // Center page number
            doc.text(
                `Page ${i} of ${pageCount}`,
                pageWidth / 2,
                pageHeight - 8,
                { align: 'center' }
            );

            // Right footer with timestamp
            const timestamp = new Date().toLocaleString();
            doc.text(
                `Generated: ${timestamp}`,
                pageWidth - 15,
                pageHeight - 8,
                { align: 'right' }
            );
        }

        // Save with formatted filename
        const dateStr = new Date().toISOString().split('T')[0];
        const timeStr = new Date().toTimeString().split(' ')[0].replace(/:/g, '-');
        doc.save(`SmartLibrary_${activeTab}_${dateStr}_${timeStr}.pdf`);
    };
    // Filter data
    const filteredData = (activeTab === "requests" ? requests : issues).filter((item: any) => {
        const patron = activeTab === "requests" ? item.requestedBy : item.studentId;
        const searchLower = searchTerm.toLowerCase();
        return patron?.name?.toLowerCase().includes(searchLower) ||
            item.bookId?.title?.toLowerCase().includes(searchLower) ||
            patron?.rollNumber?.toLowerCase().includes(searchLower) ||
            patron?.staffId?.toLowerCase().includes(searchLower);
    });

    if (loading) {
        return (
            <div className="min-h-screen bg-white flex items-center justify-center">
                <div className="text-center">
                    <div className="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
                    <p className="text-black font-medium">Loading library data...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-white p-6">
            <div className="max-w-7xl mx-auto">

                {/* Header - Simplified */}
                <div className="mb-8">
                    <h1 className="text-3xl font-bold text-black">Library Administration</h1>
                    <p className="text-gray-700 text-lg mt-1">Manage all requests and book issues</p>
                </div>

                {/* Statistics Cards - High Contrast */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-5 mb-8">
                    <div className="bg-blue-50 p-5 rounded-lg border-2 border-blue-200">
                        <div className="flex items-center justify-between mb-2">
                            <BookOpen className="w-6 h-6 text-blue-700" />
                            <span className="text-3xl font-bold text-blue-900">{totalRequests}</span>
                        </div>
                        <p className="text-blue-800 font-medium text-lg">Total Requests</p>
                        <p className="text-blue-700 text-sm mt-1">{pendingRequests} pending approval</p>
                    </div>

                    <div className="bg-green-50 p-5 rounded-lg border-2 border-green-200">
                        <div className="flex items-center justify-between mb-2">
                            <CheckCircle className="w-6 h-6 text-green-700" />
                            <span className="text-3xl font-bold text-green-900">{approvedRequests}</span>
                        </div>
                        <p className="text-green-800 font-medium text-lg">Approved</p>
                        <p className="text-green-700 text-sm mt-1">Ready for collection</p>
                    </div>

                    <div className="bg-purple-50 p-5 rounded-lg border-2 border-purple-200">
                        <div className="flex items-center justify-between mb-2">
                            <Users className="w-6 h-6 text-purple-700" />
                            <span className="text-3xl font-bold text-purple-900">{totalIssues}</span>
                        </div>
                        <p className="text-purple-800 font-medium text-lg">Total Issues</p>
                        <p className="text-purple-700 text-sm mt-1">{activeIssues} currently active</p>
                    </div>

                    <div className="bg-amber-50 p-5 rounded-lg border-2 border-amber-200">
                        <div className="flex items-center justify-between mb-2">
                            <AlertCircle className="w-6 h-6 text-amber-700" />
                            <span className="text-3xl font-bold text-amber-900">{overdueIssues}</span>
                        </div>
                        <p className="text-amber-800 font-medium text-lg">Overdue Books</p>
                        <p className="text-amber-700 text-sm mt-1">Require immediate attention</p>
                    </div>
                </div>

                {/* Controls - Simplified */}
                <div className="bg-gray-50 rounded-lg border-2 border-gray-300 mb-6">
                    <div className="p-4 border-b-2 border-gray-300">
                        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                            {/* Tab Switcher */}
                            <div className="flex bg-white rounded-lg border-2 border-gray-300 p-1">
                                <button
                                    onClick={() => setActiveTab("requests")}
                                    className={`px-6 py-2.5 rounded-md text-base font-bold transition-colors ${activeTab === "requests"
                                        ? "bg-blue-600 text-white"
                                        : "bg-white text-gray-800 hover:bg-gray-100"
                                        }`}
                                >
                                    REQUESTS ({requests.length})
                                </button>
                                <button
                                    onClick={() => setActiveTab("issues")}
                                    className={`px-6 py-2.5 rounded-md text-base font-bold transition-colors ${activeTab === "issues"
                                        ? "bg-blue-600 text-white"
                                        : "bg-white text-gray-800 hover:bg-gray-100"
                                        }`}
                                >
                                    ISSUES ({issues.length})
                                </button>
                            </div>

                            {/* Export Buttons */}
                            <div className="flex gap-3">
                                <button
                                    onClick={handlePDFExport}
                                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-white border-2 border-gray-400 text-gray-800 rounded-md text-base font-medium hover:bg-gray-100"
                                >
                                    <FileText className="w-5 h-5" />
                                    Export PDF
                                </button>
                                <button
                                    onClick={handleExcelExport}
                                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-white border-2 border-gray-400 text-gray-800 rounded-md text-base font-medium hover:bg-gray-100"
                                >
                                    <TableIcon className="w-5 h-5" />
                                    Export Excel
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* Search */}
                    <div className="p-4">
                        <div className="relative">
                            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-700" />
                            <input
                                type="text"
                                placeholder={`Search by name, book title, or ID...`}
                                className="w-full pl-12 pr-5 py-3 bg-white border-2 border-gray-400 rounded-lg text-base text-black placeholder-gray-600 focus:outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-200"
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                            />
                        </div>
                    </div>
                </div>

                {/* Table - High Contrast */}
                <div className="bg-white rounded-lg border-2 border-gray-400 overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full">
                            <thead className="bg-gray-800">
                                <tr>
                                    <th className="px-6 py-4 text-left text-sm font-bold text-white uppercase">User</th>
                                    <th className="px-6 py-4 text-left text-sm font-bold text-white uppercase">Book Details</th>
                                    <th className="px-6 py-4 text-left text-sm font-bold text-white uppercase">Dates</th>
                                    <th className="px-6 py-4 text-left text-sm font-bold text-white uppercase">Fine</th>
                                    <th className="px-6 py-4 text-left text-sm font-bold text-white uppercase">Status</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y-2 divide-gray-300">
                                {filteredData.length > 0 ? (
                                    filteredData.map((item: any, index: number) => {
                                        const patron = activeTab === "requests" ? item.requestedBy : item.studentId;
                                        const isOverdue = activeTab === "issues" && !item.returned && new Date(item.returnDate) < new Date();

                                        return (
                                            <tr key={item._id} className={`${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'} hover:bg-blue-50`}>
                                                <td className="px-6 py-4">
                                                    <div className="flex items-center">
                                                        <div className="w-10 h-10 bg-gray-700 rounded-full flex items-center justify-center text-white font-bold text-lg mr-3">
                                                            {patron?.name?.charAt(0) || 'U'}
                                                        </div>
                                                        <div>
                                                            <div className="text-base font-bold text-black">{patron?.name}</div>
                                                            <div className="text-sm text-gray-700">
                                                                {patron?.rollNumber || patron?.staffId || 'No ID'}
                                                            </div>
                                                            <div className="text-sm text-gray-600">{patron?.email}</div>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td className="px-6 py-4">
                                                    <div className="text-lg font-bold text-black">{item.bookId?.title}</div>
                                                    <div className="text-base text-gray-800">by {item.bookId?.author}</div>
                                                    <div className="text-sm text-gray-700 font-mono mt-1">ID: {item.bookId?.bookId}</div>
                                                </td>
                                                <td className="px-6 py-4">
                                                    <div className="text-base text-black">
                                                        <span className="font-medium">Created:</span> {new Date(item.createdAt || item.issueDate).toLocaleDateString()}
                                                    </div>
                                                    <div className={`text-base mt-1 ${isOverdue ? 'text-red-700 font-bold' : 'text-black'}`}>
                                                        <span className="font-medium">Due:</span> {new Date(item.returnDate).toLocaleDateString()}
                                                        {isOverdue && ' ⚠️ OVERDUE'}
                                                    </div>
                                                </td>
                                                <td className="px-6 py-4">
                                                    <div className="text-xl font-bold text-black">₹{item.fineAmount}</div>
                                                    <div className={`text-base font-medium mt-1 ${item.finePaid ? 'text-green-700' : 'text-orange-700'}`}>
                                                        {item.finePaid ? '✓ PAID' : '⏳ PENDING'}
                                                    </div>
                                                </td>
                                                <td className="px-6 py-4">
                                                    {activeTab === "requests" ? (
                                                        <span className={`inline-flex px-3 py-1.5 text-sm font-bold rounded ${item.status === 'approved' ? 'bg-green-200 text-green-900 border-2 border-green-700' :
                                                            item.status === 'rejected' ? 'bg-red-200 text-red-900 border-2 border-red-700' :
                                                                'bg-yellow-200 text-yellow-900 border-2 border-yellow-700'
                                                            }`}>
                                                            {item.status.toUpperCase()}
                                                        </span>
                                                    ) : (
                                                        <span className={`inline-flex items-center gap-2 text-base font-bold ${item.returned ? 'text-green-700' :
                                                            isOverdue ? 'text-red-700' : 'text-blue-700'
                                                            }`}>
                                                            {item.returned ? (
                                                                <><CheckCircle className="w-5 h-5" /> RETURNED</>
                                                            ) : (
                                                                <><Clock className="w-5 h-5" /> {isOverdue ? 'OVERDUE' : 'ACTIVE'}</>
                                                            )}
                                                        </span>
                                                    )}
                                                </td>
                                            </tr>
                                        );
                                    })
                                ) : (
                                    <tr>
                                        <td colSpan={5} className="px-6 py-16 text-center">
                                            <p className="text-xl text-black font-medium">
                                                {searchTerm ? 'No matching records found' : `No ${activeTab} available`}
                                            </p>
                                            <p className="text-gray-700 text-base mt-2">
                                                {searchTerm ? 'Try adjusting your search terms' : 'Check back later for updates'}
                                            </p>
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>

                    {/* Footer */}
                    <div className="bg-gray-800 px-6 py-4 border-t-2 border-gray-400">
                        <div className="flex items-center justify-between text-base">
                            <span className="text-white font-medium">
                                Showing <span className="font-bold text-white">{filteredData.length}</span> of{' '}
                                <span className="font-bold text-white">
                                    {activeTab === "requests" ? requests.length : issues.length}
                                </span> records
                            </span>

                            <span className="text-white font-bold">
                                Total Fine: ₹{filteredData.reduce((sum, item) => sum + (item.fineAmount || 0), 0)}
                            </span>
                        </div>
                    </div>
                </div>

                {/* Footer Note */}
                <p className="text-base text-gray-800 mt-4 text-center border-t-2 border-gray-300 pt-4">
                    Last updated: {new Date().toLocaleString()}
                </p>
            </div>
        </div>
    );
}